version: 2

defaults: &defaults
  working_directory: ~/halogen-portal
  docker:
    - image: circleci/node:10.15-browsers
  environment:
    RTS_ARGS: +RTS -N2 -RTS

jobs:
  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
            - v0.1-yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - v0.1-yarn-cache-{{ .Branch }}
            - v0.1-yarn-cache-

      - restore_cache:
          keys:
            - v0.1-packages-cache-{{ .Branch }}-{{ checksum "packages.dhall" }}
            - v0.1-packages-cache-{{ .Branch }}
            - v0.1-packages-cache-

      - run:
          name: Install PureScript and NPM dependencies
          command: yarn # relies on postinstall

      - save_cache:
          key: v0.1-yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/halogen-portal/node_modules

      - save_cache:
          key: v0.1-packages-cache-{{ .Branch }}-{{ checksum "packages.dhall" }}
          paths:
            - ~/halogen-portal/.spago

      - run:
          name: Verify code formatting completes (TODO: Commit any diffs)
          command: yarn format

      - run:
          name: Verify the project builds successfully
          command: spago build --no-install

      - run:
          name: Verify the examples build successfully
          command: spago build --no-install -p './example/**/*.purs`'

      - run:
          name: Verify the tests pass
          command: spago test

workflows:
  version: 2
  build:
    jobs:
      - test
